### ISSUE TITLE
Transmission starts before USB mount

### ISSUE THREAD

**Issue by reloweb** [thoradia/LibreELEC.tv#11]
Hi,
in the old version of the addon Transmission, it works smootly. With this, transmission starts before USB mount and torrents in queue doesn't start until I'll do it manually.

**Comment by thoradia** [comment]
Thank you for the feedback, I will look into it.
In the meantime, create shell script /storage/.kodi/userdata/addon_data/service.transmission/init.sh to wait for USB mounts, for example with command sleep 5.

**Comment by thoradia** [comment]
system.d units have been updated to start after muti-user.target (transmission from revision 8 onwards).
Does this fix the problem @reloweb ?

**Comment by reloweb** [comment]
It seems ok now. Thanks!
