### ISSUE TITLE
Request: port rTorrent

### ISSUE THREAD

**Issue by sal666** [thoradia/LibreELEC.tv#14]
Hi,
please port rTorrent+ruTorrent service to LibreELEC for RPi2. Current addon is maintained by sraue and only works in OE.

**Comment by TheUglyOne** [comment]
I would love to see this for the ODROID-C2, as well.

**Comment by MaxSchouten** [comment]
This would be epic!

**Comment by kimme** [comment]
This would be useful, because rutorrent has the ability to move the finished transfer to an new directory..

**Comment by maxonly1** [comment]
yes please! +1

**Comment by thoradia** [comment]
I have pushed a stripped down rTorrent add-on for LibreELEC 8.0.
Stripped down means only rtorrent and minimal Kodi add-on settings.
I intend to ship ruTorrent as a separate service add-on.

The add-on comes with the rtorrent-ctl wrapper:
rtorrent-ctl cli re-attaches to the rtorrent screen (ctrl-a d to detach),
rtorrent-ctl config allows to edit rtorrent.rc and restart rtorrent.

**Comment by maxonly1** [comment]
Great job. Communication between rTorrent and rutorrent will be tricky. Look forward to your progress. Thnx

**Comment by thoradia** [comment]
rTorrent revision 2 fixes and enables xmlrpc. It works out of the box with the rTorrent add-on from the Kodi Add-on repository, which acts as a Kodi front-end. ruTorrent is within reach.

**Comment by thoradia** [comment]
Add-ons for rTorrent and ruTorrent are now available for all vanilla LibreELEC 8.0 projects.
The ruTorrent add-on automatically installs the rTorrent add-on.
By default, the port of the ruTorrent web user interface is 6880.

**Comment by sal666** [comment]
Wow! Great work!!
Will test and report back

**Comment by TheUglyOne** [comment]
Thanks, thoradia!! :-)

As an FYI for other users so you don't spend hours trying to troubleshoot like I did: there's a problem with rTorrent and HTTPS trackers caused by the SSL libraries used by curl. Hopefully, the 8.2 release of LibreELEC in Jul/Aug will fix the problem. https://forum.libreelec.tv/thread/2707-thoradia-add-ons/?postID=54094&highlight=curl#post54094
