### ISSUE TITLE
thoradia/8.1/S905/arm/ jackett

### ISSUE THREAD

**Issue by BaZSeE89** [thoradia/LibreELEC.tv#17]
Hy!
Pls update jackett version to latest, because current version have a problem, which fixed in latest version.
THX!

**Comment by thoradia** [comment]
I will do, soonish.
In the meantime you can replace folder /storage/.kodi/addons/service.jackett/Jackett with any appropriate release of Jackett.

**Comment by thoradia** [comment]
Done
