### ISSUE TITLE
Radarr and Sonarr not available from time to time

### ISSUE THREAD

**Issue by jul1792** [thoradia/LibreELEC.tv#18]
Hi there,

I installed the latest Libreelec on my RPi3 and installed your add ons NZBGet, Sonarr and Radarr. NZBGet works great, no issues here, but Sonarr and Radarr are not available from time to time. On my iPhone it always stucks at the loading page (with the dots dancing around). And almost every morning I have to reboot my RPi3 because one of the add ons just isn't working. Either it stucks on the loading page, or I can't add Series or Movies or the browser (Chrome) says, it isn't available.
The finished downloads are moved to a NAS, which is turned off most of the time. When I turn it on, the downloads are moved to it. Could the NAS be the cause?
My RPi3 is connected over the built in Wifi.

Maybe you can help me solve my problems. Because generally your add ons are a great solution!

**Comment by thoradia** [comment]
I have no idea what the cause of your problem may be.
Logs would provide further information. They are at:
smb://libreelec.local/userdata/addon_data/service.radarr/logs
smb://libreelec.local/userdata/addon_data/service.sonarr/logs

**Comment by thoradia** [comment]
Inactive, closing
