### ISSUE TITLE
Sickrage does not start anymore

### ISSUE THREAD

**Issue by erdincsk** [thoradia/LibreELEC.tv#20]
Hello,

My sickrage has stopped working and i can not start it anymore. 

After a new and clean installation of a libreelec v8, everything was working f,ne until i realized sickrage did not make unrar operation for a downloaded file. Then i tried to install unrar tool for kodi and i did.

After that i was able to log in webui. But sometime later i realized that sickrage does not respond and start anymore. I'm not sure that what may cause this issue.

I tried to uninstall and install it again, but no success..

`systemclt status service.sickrage`

> service.sickrage.service - SickRage
>    Loaded: loaded (/storage/.kodi/addons/service.sickrage/system.d/service.sickrage.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Tue 2017-08-01 23:45:23 +03; 7min ago
>      Docs: https://sickrage.github.io/
>   Process: 691 ExecStart=/bin/sh /storage/.kodi/addons/service.sickrage/bin/sickrage.start (code=exited, status=1/FAILURE)
>  Main PID: 691 (code=exited, status=1/FAILURE)
> 
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Unit entered failed state.
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Failed with result 'exit-code'.
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Service hold-off time over, scheduling restart.
> Aug 01 23:45:23 LibreELEC systemd[1]: Stopped SickRage.
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Start request repeated too quickly.
> Aug 01 23:45:23 LibreELEC systemd[1]: Failed to start SickRage.
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Unit entered failed state.
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Failed with result 'exit-code'.

When i checked journal during the start, i see below lines. But i still can not find the reason why sickrage does not start.
Any help will be appreciated.

> Aug 01 23:45:22 LibreELEC kernel: Bluetooth: HCI UART protocol H4 registered
> Aug 01 23:45:22 LibreELEC kernel: Bluetooth: HCI UART protocol Three-wire (H5) registered
> Aug 01 23:45:22 LibreELEC kernel: Bluetooth: HCI UART protocol Broadcom registered
> Aug 01 23:45:22 LibreELEC rpi-btuart[364]: bcm43xx_init
> Aug 01 23:45:22 LibreELEC rpi-btuart[364]: Flash firmware /etc/firmware/brcm/BCM43430A1.hcd
> Aug 01 23:45:22 LibreELEC rpi-btuart[364]: Set Controller UART speed to 921600 bit/s
> Aug 01 23:45:22 LibreELEC rpi-btuart[364]: Device setup complete
> Aug 01 23:45:22 LibreELEC systemd[1]: Reached target Bluetooth.
> Aug 01 23:45:22 LibreELEC ntfs-3g[702]: Version 2016.2.22 external FUSE 29
> Aug 01 23:45:22 LibreELEC ntfs-3g[702]: Mounted /dev/sda1 (Read-Write, label "DATA", NTFS 3.1)
> Aug 01 23:45:22 LibreELEC ntfs-3g[702]: Cmdline options: big_writes,fmask=0133,uid=0,gid=0,utf8
> Aug 01 23:45:22 LibreELEC ntfs-3g[702]: Mount options: utf8,allow_other,nonempty,relatime,default_permissions,fsname=/dev/sda1,blkdev,blksize=4096
> Aug 01 23:45:22 LibreELEC ntfs-3g[702]: Global ownership and permissions enforced, configuration type 7
> Aug 01 23:45:22 LibreELEC udevil[635]: Mounted /dev/sda1 at /media/DATA
> Aug 01 23:45:22 LibreELEC systemd[1]: Stopping Samba SMB Daemon...
> Aug 01 23:45:22 LibreELEC systemd[1]: Stopped Samba SMB Daemon.
> Aug 01 23:45:22 LibreELEC systemd[1]: Starting Samba SMB Daemon...
> Aug 01 23:45:22 LibreELEC smbd[720]: [2017/08/01 23:45:22.913622,  0] /home/chewitt/LibreELEC.80-images/build.LibreELEC-RPi2.arm-8.0.2/samba-3.6.25/source3/smbd/server.c:1130(smbd_main)
> Aug 01 23:45:22 LibreELEC smbd[720]:   standard input is not a socket, assuming -D option
> Aug 01 23:45:22 LibreELEC systemd[1]: Started Samba SMB Daemon.
> Aug 01 23:45:22 LibreELEC systemd[1]: Started Udevil mount service.
> Aug 01 23:45:23 LibreELEC sh[691]: Traceback (most recent call last):
> Aug 01 23:45:23 LibreELEC sh[691]:   File "/storage/.kodi/addons/service.sickrage/SickRage/SickBeard.py", line 66, in <module>
> Aug 01 23:45:23 LibreELEC sh[691]:     import sickbeard
> Aug 01 23:45:23 LibreELEC sh[691]:   File "/storage/.kodi/addons/service.sickrage/SickRage/sickbeard/__init__.py", line 33, in <module>
> Aug 01 23:45:23 LibreELEC sh[691]:     import rarfile
> Aug 01 23:45:23 LibreELEC sh[691]:   File "/storage/.kodi/addons/service.sickrage/SickRage/lib/rarfile/__init__.py", line 2952, in <module>
> Aug 01 23:45:23 LibreELEC sh[691]:     _check_unrar_tool()
> Aug 01 23:45:23 LibreELEC sh[691]:   File "/storage/.kodi/addons/service.sickrage/SickRage/lib/rarfile/__init__.py", line 2931, in _check_unrar_tool
> Aug 01 23:45:23 LibreELEC sh[691]:     custom_check([ORIG_UNRAR_TOOL], True)
> Aug 01 23:45:23 LibreELEC sh[691]:   File "/storage/.kodi/addons/service.sickrage/SickRage/lib/rarfile/__init__.py", line 2823, in custom_check
> Aug 01 23:45:23 LibreELEC sh[691]:     p = custom_popen(cmd)
> Aug 01 23:45:23 LibreELEC sh[691]:   File "/storage/.kodi/addons/service.sickrage/SickRage/lib/rarfile/__init__.py", line 2813, in custom_popen
> Aug 01 23:45:23 LibreELEC sh[691]:     creationflags=creationflags)
> Aug 01 23:45:23 LibreELEC sh[691]:   File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
> Aug 01 23:45:23 LibreELEC sh[691]:   File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
> Aug 01 23:45:23 LibreELEC sh[691]: OSError: [Errno 8] Exec format error
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Main process exited, code=exited, status=1/FAILURE
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Unit entered failed state.
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Failed with result 'exit-code'.
> Aug 01 23:45:23 LibreELEC sshd[686]: Accepted password for root from 192.168.1.29 port 50811 ssh2
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Service hold-off time over, scheduling restart.
> Aug 01 23:45:23 LibreELEC systemd[1]: Stopped SickRage.
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Start request repeated too quickly.
> Aug 01 23:45:23 LibreELEC systemd[1]: Failed to start SickRage.
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Unit entered failed state.
> Aug 01 23:45:23 LibreELEC systemd[1]: service.sickrage.service: Failed with result 'exit-code'.
>

**Comment by thoradia** [comment]
Your issue is likely caused by this: https://github.com/SickRage/SickRage

**Comment by erdincsk** [comment]
Hello,

I do not think that my issue is related to sickrage shutdown.

I digged into problem with my very limited linux and programming knowledge and i found that my problem is related to **unrar.**

I always received below journal messages when i tried to start sickrage

```
Aug 06 18:49:26 LibreELEC sh[2990]: Traceback (most recent call last):
Aug 06 18:49:26 LibreELEC sh[2990]:   File "/storage/.kodi/addons/service.sickrage/SickRage/SickBeard.py", line 66, in <module>
Aug 06 18:49:26 LibreELEC sh[2990]:     import sickbeard
Aug 06 18:49:26 LibreELEC sh[2990]:   File "/storage/.kodi/addons/service.sickrage/SickRage/sickbeard/__init__.py", line 33, in <module>
Aug 06 18:49:26 LibreELEC sh[2990]:     import rarfile
Aug 06 18:49:26 LibreELEC sh[2990]:   File "/storage/.kodi/addons/service.sickrage/SickRage/lib/rarfile/__init__.py", line 2952, in <module>
Aug 06 18:49:26 LibreELEC sh[2990]:     _check_unrar_tool()
Aug 06 18:49:26 LibreELEC sh[2990]:   File "/storage/.kodi/addons/service.sickrage/SickRage/lib/rarfile/__init__.py", line 2931, in _check_unrar_tool
Aug 06 18:49:26 LibreELEC sh[2990]:     custom_check([ORIG_UNRAR_TOOL], True)
Aug 06 18:49:26 LibreELEC sh[2990]:   File "/storage/.kodi/addons/service.sickrage/SickRage/lib/rarfile/__init__.py", line 2823, in custom_check
Aug 06 18:49:26 LibreELEC sh[2990]:     p = custom_popen(cmd)
Aug 06 18:49:26 LibreELEC sh[2990]:   File "/storage/.kodi/addons/service.sickrage/SickRage/lib/rarfile/__init__.py", line 2813, in custom_popen
Aug 06 18:49:26 LibreELEC sh[2990]:     creationflags=creationflags)
Aug 06 18:49:26 LibreELEC sh[2990]:   File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
Aug 06 18:49:26 LibreELEC sh[2990]:   File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
Aug 06 18:49:26 LibreELEC sh[2990]: OSError: [Errno 8] Exec format error
```


But when i comment the code in "/storage/.kodi/addons/service.sickrage/SickRage/lib/rarfile/__init__.py", line 2931, in _check_unrar_tool, my sicrage starts without any problem but this time it does not recognize unrar.

When i select "Unpack" option in post proccessing options, it says "unrar executable not found".

I could not go further from this point to achieve a complete solution for my problem.

Any help will be appreciated.

Thanks a lot!

**Comment by erdincsk** [comment]
Hello, 

I realized that unrar tool which I have installed from superrepo was a old version of unrar. I found a newer version of unrar tool and replaced it with old one. After that sickrage was working fine.
