### ISSUE TITLE
transmission settings.json 

### ISSUE THREAD

**Issue by pstyrna** [thoradia/LibreELEC.tv#21]
Hi,
Changes in /storage/.kodi/userdata/addon_data/service.transmission/setting.json are reverted each time after transmission starts. 
ex.
change in settings.json -> reboot -> settings reverted

transmission disable -> change in settings.json -> reboot -> settings ok -> transmission enable -> reboot -> settings reverted

Settings from webgui are preserved.

**Comment by thoradia** [comment]
Which settings are you trying to change?
Settings from web UI override those from settiings.json

**Comment by pstyrna** [comment]
Hi I was trying to change incomplete dir.

**Comment by thoradia** [comment]
Incomplete dir should be set through web ui. Value from web ui overrides that of settings.json. You can disable incomplete dir via web ui: set 'separate incomplete torrents' to false.

**Comment by pstyrna** [comment]
Sorry but I cannot see option to change incomplete dir in webui only download dir 
![image](https://user-images.githubusercontent.com/26505393/29430318-419c10de-8394-11e7-994e-c7d25aa3d879.png)

**Comment by thoradia** [comment]
Hm, sorry, my bad... incomplete dir should be set from Kodi UI, and can be disabled via Kodi UI.

**Comment by pstyrna** [comment]
Yeah its there thx, youcan close the issue

**Comment by thoradia** [comment]
Great!
