### ISSUE TITLE
Transmission miss libssl.so on LibreELEC 8.1.0

### ISSUE THREAD

**Issue by i3laze** [thoradia/LibreELEC.tv#22]
I've just updated from 8.0.2 to 8.1.0 (Wetek Play 2).
As LE moved from LibreSSL to OpenSSL.. I guess they messed with libssl in the system.

Starting service manually now gives an error:

> transmission-daemon: error while loading shared libraries: libssl.so.39: cannot open shared object file: No such file or directory

I've deleted v8.1.13 package and now I'm unable to reinstall it - nothing just happens on clicking Install.

How about rebuilding a Transmission service ASAP?)) (or opening a detailed ticket on LibreELEC git)

**Comment by thoradia** [comment]
Have you installed and updated the Thoradia Add-ons add-on? If so, what is shown in Add-ons/My add-ons/Services/Thoradia Add-ons/Configure?

**Comment by i3laze** [comment]
Yes, the Thoradia Add-ons exists and stated as v8.1.9.
It's status says:
> LibreELEC    8.2/WeTek_Play_2/aarch64
> Thoradia    8.2/Odroid_C2/aarch64

Bumping manual update for repository fixed the mess.
Now add-on is v8.**2**.9 and Transmission has successfully reinstalled!
Thanks for the clue.
