### ISSUE TITLE
Add Deluge

### ISSUE THREAD

**Issue by gurabli** [thoradia/LibreELEC.tv#3]
Hi, 
Is it possible to add Deluge daemon and Web ui, with Deluge console?

**Comment by thoradia** [comment]
Request noted. Deluge however has too many dependencies and therefore represents too great a development/maintenance effort to be considered at the moment. Closing.

**Comment by gurabli** [comment]
Sorry to hear, but I understand. Btw, did you think about docker or Deluge as an add on?
