### ISSUE TITLE
Chrome Browser

### ISSUE THREAD

**Issue by Wheemer** [thoradia/LibreELEC.tv#30]
There is a version of chrome browser that works within libreelec. I thought it would be nice to include in on your repo, and maybe even tweak it to work better?

**Comment by thoradia** [comment]
LibreELEC provides [Chromium for Generic](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/browser/chromium/package.mk). I have no plan to build Chrome. Team LibreELEC maybe? Closing.
