### ISSUE TITLE
Update Jackett

### ISSUE THREAD

**Issue by ghost** [thoradia/LibreELEC.tv#31]
Hello,

Your version of jackett is  out dated and no more compatible with yggTorrent. Is it possible to updare it ?

Many thanks !

**Comment by thoradia** [comment]
Jackett should autoupdate.

To update manually:
- connect to Jackett web user interface (port 9117)
- click on `Check for updates`
- click on `View logs`

If this does not work, provide a log (from `userdata/addon_data/service.jackett/Jackett/log.txt`)

**Comment by thoradia** [comment]
No feedback, closing
