### ISSUE TITLE
pivpn request

### ISSUE THREAD

**Issue by rijkie** [thoradia/LibreELEC.tv#32]
The purpose for this request is to be able to use pivpn to create a vpn server using libreelec on a raspberry pi. Is this possible? I posted for help on pivpn github [https://github.com/pivpn/pivpn/issues/438](https://github.com/pivpn/pivpn/issues/438) .

**Comment by thoradia** [comment]
It is possible, but...
LibreELEC provides openvpn without server mode, and this is unlikely to change.
I could wrap openvpn with server mode in an add-on, but I am not interested to provide (understand, package and test) the pivpn scripts.

**Comment by rijkie** [comment]
Are you saying that you are willing to create openvpn with server mode in an add-on? And that fulfills my request. If yes. Yes I would want that.  
Also pipnv has pi-hole integrated into vpn. But seeing a post on [libreELEC forums pi-hole](https://forum.libreelec.tv/thread/10262-pi-hole/) that is not possible?

I don't know if this is related or helps or not. But I found a post on OSMC. Which said that they are working on a [VPN solution for OSMC](https://discourse.osmc.tv/t/pi-hole-and-pivpn/40018).

**Comment by thoradia** [comment]
I will wrap openvpn with server mode in an add-on when I find the time

**Comment by alonpeer** [comment]
Hi @thoradia @rijkie ,

I'm also interested in running an OpenVPN server on my raspberry pi under LibreELEC. Can I somehow help promote, contribute and resolve this issue? Are there any instructions of how to wrap something in an add-on?

**Comment by alonpeer** [comment]
Scratch that. I was able to use https://hub.docker.com/r/giggio/openvpn-arm/, as suggested to me here: https://github.com/ljishen/pivpn-docker/issues/1#issuecomment-453808211

**Comment by thoradia** [comment]
Use docker
