### ISSUE TITLE
Missing quotes around $@

### ISSUE THREAD

**Issue by screw** [thoradia/LibreELEC.tv#34]
https://github.com/thoradia/LibreELEC.tv/blob/ea6e8540f5f0a1cc77ae9c0d5e24116cf5197b3b/packages/thoradia/addons/flexget/source/bin/flexget.ctl#L14

Missing quotes around $@ causes the shell to expand a string with space into two arguments to the flexget_vanilla.py
E.g 
flexget.ctl -c config.yml series show "Some Show"
There is a FlexGet process already running for this config, sending execution there.
usage: flexget [-h] [-V] [--test] [-c CONFIG] [--logfile LOGFILE]
               [--loglevel LEVEL] [--bugreport] [--profile [OUTFILE]] [--cron]
               [--debug-warnings] [--debug-db-sessions]
               <command> ...
flexget: error: unrecognized arguments: Show

**Comment by thoradia** [comment]
Thanks, will fix
