### ISSUE TITLE
Unable to connect to repo in LibreELEC 9 alpha

### ISSUE THREAD

**Issue by RedSquirrel87** [thoradia/LibreELEC.tv#38]
I installed the repo in my LibreELEC 8.90.5 (9.0) alpha, but when I try to enter in the repository it gives me an error that it could not connect to it.
In the kodi.log I found these lines that could explain the issue:

> 09:52:20.566 T:3893318528   ERROR: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/thoradia/thoradia/master/9.0.1/RPi2/arm/addons.xml.md5
> 09:52:20.570 T:3893318528   ERROR: Open - failed to open source <https://raw.githubusercontent.com/thoradia/thoradia/master/9.0.1/RPi2/arm/addons.xml.md5>
> 09:52:20.571 T:3893318528   ERROR: CRepository: failed read 'https://raw.githubusercontent.com/thoradia/thoradia/master/9.0.1/RPi2/arm/addons.xml.md5'
> 09:52:20.810 T:3893318528   DEBUG: CRepositoryUpdater: done.
> 09:52:20.813 T:3211510656   DEBUG: CAddonDatabase: SELECT repo.id FROM repo .. took 3 ms
> 09:52:20.813 T:3211510656   DEBUG: CAddonDatabase: no valid repository matching 'service.thoradia'

It seems that the LibreELEC alpha use 9.0.1 as version and since in the repository there is only 9.0 (without the .1) it can not find the file returning 404.
I tried to change manually the version in the files but when it auto-updates itself the issue returns.

**Comment by thoradia** [comment]
A temporary workaround is to delete `/storage/.kodi/addons/service.thoradia/default.py`.

**Comment by thoradia** [comment]
See #44
