### ISSUE TITLE
Mono Tools LE 9 Nightly

### ISSUE THREAD

**Issue by Morphy99** [thoradia/LibreELEC.tv#39]
Hi I'm just setting up a new Gemini Lake based system so having to use a milhouse nightly LE build. Have an issue installing Sonarr:

The dependency on tools.mono version 0.0.0 could not be satisfied.

Also have another issue accessing other apps with this error when I browse to the port:
400 Bad Request
Illegal cookie name CSRF-Token-VCA6E

Traceback (most recent call last):
  File "./cherrypy/_cprequest.py", line 635, in respond
  File "./cherrypy/_cprequest.py", line 737, in process_headers
HTTPError: (400, 'Illegal cookie name CSRF-Token-VCA6E')

**Comment by Morphy99** [comment]
Sorry the 400 Bad Request was a local cookie issue on my PC however the dependency issue for Mono is still not resolved.
I've been looking into it and I have managed to install [this](https://libreelec.adamg.co.uk/addons/9.0.1/LePotato/arm/tools.mono/) however its for ARM so probably not compatible. Sonarr installs now however doesn't run so guessing it hasnt done the trick.

**Comment by Morphy99** [comment]
Ok so I've fudged this by grabbing the tools.mono from a 8.2 LE and changed the addon.xml to say 9.0 and seems to be working! If anyone wants this to save you a bit of time grab it [here](https://www.dropbox.com/s/74adk9saw9qfqoc/tools.mono-8.2.109.zip?dl=1) :grinning:

**Comment by Morphy99** [comment]
There is one more issue with sonarr:
MediaInfo Library could not be loaded libmediainfo.so.0
I've turned off analysing video files for now for it to work.

**Comment by Wheemer** [comment]
Did you add the repo to install this? Because the repo would have downloaded mono tools automatically. Also there has been a recent update to address that error.

Double check your install method, because it seems you might have made it harder than it needed to be.

**Comment by Morphy99** [comment]
Yep I downloaded the add-on service.thoradia which installed the repo and
then tried installing from there.

**Comment by thoradia** [comment]
Install [this](https://github.com/thoradia/thoradia/raw/master/9.0/Generic/x86_64/service.thoradia/service.thoradia-9.0.17.zip)

**Comment by Morphy99** [comment]
I think its the same I got from [here](https://raw.githubusercontent.com/thoradia/thoradia/master/service.thoradia.zip). I've tried it anyway and still have the libmedia error. Tried uninstalling everything and cant install Sonarr again due to tools.mono dependency missing.

**Comment by thoradia** [comment]
What happens when you try to install Thoradia Mono Tools from the repository?

**Comment by Morphy99** [comment]
I think it fails with missing dependency as well. I'm going to try it with another more recent Milhouse build and a fresh install to eliminate anything that might be interfering.

**Comment by Morphy99** [comment]
Can confirm this issue is present on a fresh LE install and on the latest LE build: LibreELEC-Generic.x86_64-9.0-Milhouse-20180323210345-#0323-g7c4674a

**Comment by Morphy99** [comment]
Looks like the libmedia error is fixed in the [latest LE9 build](http://milhouse.libreelec.tv/builds/master/Generic/LibreELEC-Generic.x86_64-9.0-Milhouse-20180328210245-%230328-gcb9786e.tar)
Still have mono tools dependency issue when installing however

**Comment by thoradia** [comment]
This is a Kodi bug: click OK when depencies are requested

**Comment by Morphy99** [comment]
It may be. I know that dependencies wouldn't install when this was opened.
Not sure about in latest builds as I worked around it.

Seb Palacio
