### ISSUE TITLE
Add Jackett

### ISSUE THREAD

**Issue by gurabli** [thoradia/LibreELEC.tv#4]
Now that Sonarr is available (so much thanks) is it posaible to add Jackett?

**Comment by thoradia** [comment]
Jackett should work out of the box on LibreELEC 8 with Mono.
I however have no experience whatsoever with Jackett.
Download it, try to run it manually and report how it should run (command line options) and I will wrap it in an add-on.
Looking forward to your feedback.

**Comment by gurabli** [comment]
Great, I will try it and see how it works, then report back here.

**Comment by gurabli** [comment]
Sorry, forgot to ask, can I try on LE Jarvis stable latest, or has to be LE Krypton alpha?

**Comment by thoradia** [comment]
Jackett added
