### ISSUE TITLE
can't start service transmission on amlogic s912

### ISSUE THREAD

**Issue by wodgey** [thoradia/LibreELEC.tv#41]
I'm getting an error;-

# sh /storage/.kodi/addons/service.transmission/bin/transmission.start
net.core.rmem_max = 4194304
net.core.wmem_max = 1048576
nice: can't execute 'transmission-daemon': No such file or directory.

I have tried the aarch64 variants for both 9 and 8.2 with the same issue.

(it works beautifully on x86_64 by the way. very happy with it on a small little Asus Revo box)

**Comment by wodgey** [comment]
Do you need the kodi.log, systemctl status service.transmission & journalctl -xe grabs?

**Comment by thoradia** [comment]
Are you using CoreELEC?

**Comment by wodgey** [comment]
Yes I am.
It works perfectly on x86_x64 8.2.5 LE though

**Comment by thoradia** [comment]
See #44

**Comment by wodgey** [comment]
AWESOME!!!!!

Thanks dude. 
Confirmed working

**Comment by thoradia** [comment]
Spread the word
