### ISSUE TITLE
qBittorrent don't save SSL certificates

### ISSUE THREAD

**Issue by 97carmine** [thoradia/LibreELEC.tv#42]
Hello

When trying HTTPs settings to WebUI using this [tutorial](https://github.com/qbittorrent/qBittorrent/wiki/Linux-WebUI-setting-up-HTTPS-with-self-signed-SSL-certificates). WebUI does not save the added keys

**Comment by thoradia** [comment]
Ask at qBittorrent and report here if the issue is with the add-on

**Comment by thoradia** [comment]
This should be fixed in revision 15 of the qbittorrent add-on
