### ISSUE TITLE
Nzbget & Couchpatato PP Failure

### ISSUE THREAD

**Issue by Rockfordgun** [thoradia/LibreELEC.tv#48]
Hi guys 

Have a small issue that im trying to rectify.
My downloads run fine after the downloads auto processing is also fine but for some reason nzbget always gives a PP Failure on my movies that goes via couchpatato renaming process everything works but still it gives me a error any ideas?

> INFO | Fri Aug 24 2018 08:10:26 | Collection Death.Wish.2018.720p.BluRay.DTS.x264.1-LEGi0N-Obfuscated.cp(tt1137450) added to history
-- | -- | --
ERROR | Fri Aug 24 2018 08:10:26 | Post-process-script nzbToMedia.py for Death.Wish.2018.720p.BluRay.DTS.x264.1-LEGi0N-Obfuscated.cp(tt1137450) failed
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:26] [ERROR]::MAIN: A problem was reported in the /storage/.kodi/userdata/addon_data/script.service.audo/scripts/nzbToMedia.py script.
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:26] [ERROR]::MAIN: Remote Path is enabled for CouchPotato:Movies but no Network mount points are defined. Please check your autoProcessMedia.cfg, exiting!
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:26] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:25] [INFO]::MAIN: Script triggered from NZBGet Version 19.1.
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:25] [INFO]::MAIN: #########################################################
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:25] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:25] [INFO]::MAIN: #########################################################
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:25] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:25] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
INFO | Fri Aug 24 2018 08:10:26 | nzbToMedia: [08:10:25] [INFO]::MAIN: nzbToMedia Version:11.03 Branch:master (Linux 4.11.12)
INFO | Fri Aug 24 2018 08:10:25 | nzbToMedia: [08:10:25] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not
INFO | Fri Aug 24 2018 08:10:23 | nzbToMedia: [08:10:23] [INFO]::MAIN: Checking if source needs an update
INFO | Fri Aug 24 2018 08:10:23 | nzbToMedia: [08:10:23] [INFO]::MAIN: Checking database structure...
INFO | Fri Aug 24 2018 08:10:21 | Executing post-process-script nzbToMedia.py for Death.Wish.2018.720p.BluRay.DTS.x264.1-LEGi0N-Obfuscated.cp(tt1137450)

**Comment by thoradia** [comment]
LibreELEC 9 does not ship ffmpeg anymore.
Install the FFmpeg Tools add-on from the LibreELEC Add-ons repository and reboot.
It this fixes your issue, I will add a dependency to FFmpeg Tools to CouchPotato.

**Comment by Rockfordgun** [comment]
I got it sorted.
Nzbtomedia changed from renamer to manage and i changed the naming convention looks like it did the trick. Ill add the addon just for incase aswell.

Thx for the help

**Comment by thoradia** [comment]
Thank you for the feedback. Closing.
