### ISSUE TITLE
transmission

### ISSUE THREAD

**Issue by pajretX** [thoradia/LibreELEC.tv#5]
Please add a variable to indicate a path to a user specific config file.
Once enabled all the other variables would be omitted.

**Comment by thoradia** [comment]
edit /storage/.kodi/userdata/addon_data/service.transmission/settings.json via ssh/smb

**Comment by pajretX** [comment]
As easy as that... ;-) 
I'm fine with this solution ;-) 

Thank you for a reply!

Wysłano ze smartfonu Sony Xperia™

---- Użytkownik Thoradia Quack napisał ----
