### ISSUE TITLE
Prevent suspend while downloading [NZBGET]

### ISSUE THREAD

**Issue by alsdfjldafsjalsfjk** [thoradia/LibreELEC.tv#50]
Hi, is it possible for nzbget/thoradia to prevent suspend triggered by kodi while downloading? **edit**: and possibly during postprocess as well?

**Comment by thoradia** [comment]
NZBGet allows to schedule scripts
Kodi provides built-in commands (to suspend, to hibernate, to change settings, etc.)
You could maybe combine them, e.g., suspend at 3:am

**Comment by alsdfjldafsjalsfjk** [comment]
hmm ok, ill check that out, thanks!

**Comment by thoradia** [comment]
Inactive, closing
