### ISSUE TITLE
Update Medusa

### ISSUE THREAD

**Issue by kebogaer** [thoradia/LibreELEC.tv#51]
Hi,

I am wondering whether the update function should work on your addons?
I previously installed sickrage, and I had issues there as well.
When I check for upgrade, it just returns to the homepage of Medusa, the version number is "empty" .

Should the regular update function in the program work, or is there some kind of workaround for this?

Thx

K

**Comment by thoradia** [comment]
You should be able to update Medusa from the web-ui (Tools/Check For Updates)
You can check the installed version from the web-ui (Settings/Help & Info)
What does Help & Info show?
Please provide information about your installation (xELEC system and version)

**Comment by kebogaer** [comment]
![image](https://user-images.githubusercontent.com/12339594/48121910-829ac700-e276-11e8-9305-429e2b592ed1.png)
I have an rPI2 (or 3 not quite sure)

If I push update, it says in the log: no update needed
I have to say this is a fresh install, so I think I have read somewhere that the version stays empty until you first upgrade, so not sure about that.
But I raised this ticket because with sickRage I also had continuous problems with updating the system ...

**Comment by thoradia** [comment]
Your Medusa is up-to-date (to confirm, see https://github.com/pymedusa/Medusa/commits/master)
You are correct: Medusa needs an update after first install

Please close this issue unless you have other related questions

**Comment by kebogaer** [comment]
Thanks for your help, I will close
