### ISSUE TITLE
Rockchip support

### ISSUE THREAD

**Issue by ijaureguialzo** [thoradia/LibreELEC.tv#53]
Hello, tried to install add-ons from the repository on a Rockchip board (Pine Rock64) but the chip it's using (RK3328) doesn't seem to be supported.

```
12:08:58.520 T:3991921520   ERROR: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/thoradia/thoradia/master/9.0/RK3328/arm/addons.xml.md5:
12:08:58.525 T:3991921520   ERROR: Open - failed to open source <https://raw.githubusercontent.com/thoradia/thoradia/master/9.0/RK3328/arm/addons.xml.md5>
12:08:58.525 T:3991921520   ERROR: CRepository: failed read 'https://raw.githubusercontent.com/thoradia/thoradia/master/9.0/RK3328/arm/addons.xml.md5'
```

Are there plans to add support for it?. It will be an officially  supported chip on LE 9.0.

Thanks!

**Comment by thoradia** [comment]
Rockchip is not yet supported
It should soon be

**Comment by thoradia** [comment]
Try this https://github.com/thoradia/thoradia/raw/master/9.0/RK3328/arm/service.thoradia/service.thoradia-9.0.19.zip

**Comment by ijaureguialzo** [comment]
Just tried to install transmission service on the latest official LE build and it works.

Test setup: 
- Pine Rock64 board.
- LibreELEC (official): 8.90.010 (RK3328.arm).
- transmission add-on from thoradia-9.0.19.zip.


Thanks!

**Comment by thoradia** [comment]
Thank you for the feedback
I will close this after I have updated the bootstrap add-on
