### ISSUE TITLE
[request] 'deluge-client' python module

### ISSUE THREAD

**Issue by konstiv73** [thoradia/LibreELEC.tv#57]
Hello,
Please, add Python 2.7 module 'deluge-client'. It's for flexget&deluge automation.
flexget.log:
CRITICAL task          web-site        deluge-client >=1.5 is required. `pip install deluge-client` to install.
WARNING  task          web-site        Aborting task (plugin: deluge)

**Comment by thoradia** [comment]
I added deluge-client to flexget
Be aware that I was unable to update flexget because some dependencies now rely on setuptools_scm

**Comment by Superpiffer** [comment]
I have this error:
```
Apr 05 09:46:48 LibreELEC systemd[1]: Started FlexGet.
Apr 05 09:46:51 LibreELEC systemd[1]: Stopping FlexGet...
Apr 05 09:47:11 LibreELEC sh[27599]: Traceback (most recent call last):
Apr 05 09:47:11 LibreELEC sh[27599]:   File "/storage/.kodi/addons/service.flexget/bin/flexget_vanilla.py", line 3, in <module>
Apr 05 09:47:11 LibreELEC sh[27599]:     import flexget
Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/__init__.py", line 12, in <module>
Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/manager.py", line 37, in <module>
Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/db_schema.py", line 14, in <module>
Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/database.py", line 14, in <module>
Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/json.py", line 12, in <module>
Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/plugin.py", line 11, in <module>
Apr 05 09:47:11 LibreELEC sh[27599]: ImportError: No module named pkg_resources
Apr 05 09:47:12 LibreELEC systemd[1]: service.flexget.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 09:47:14 LibreELEC sh[27628]: Traceback (most recent call last):
Apr 05 09:47:14 LibreELEC sh[27628]:   File "/storage/.kodi/addons/service.flexget/bin/flexget_vanilla.py", line 3, in <module>
Apr 05 09:47:14 LibreELEC sh[27628]:     import flexget
Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/__init__.py", line 12, in <module>
Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/manager.py", line 37, in <module>
Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/db_schema.py", line 14, in <module>
Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/database.py", line 14, in <module>
Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/json.py", line 12, in <module>
Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/plugin.py", line 11, in <module>
Apr 05 09:47:14 LibreELEC sh[27628]: ImportError: No module named pkg_resources
Apr 05 09:47:15 LibreELEC systemd[1]: service.flexget.service: Control process exited, code=exited status=1
Apr 05 09:47:15 LibreELEC systemd[1]: service.flexget.service: Failed with result 'exit-code'.
Apr 05 09:47:15 LibreELEC systemd[1]: Stopped FlexGet.

```
What's wrong? setuptools is missing for some reason...

EDIT: I discovered that all the dependencies in pre_make_target are ignored, so you can't find any of them in the latest package. Do you know why? Thanks.

**Comment by konstiv73** [comment]
> I have this error:
> 
> ```
> Apr 05 09:46:48 LibreELEC systemd[1]: Started FlexGet.
> Apr 05 09:46:51 LibreELEC systemd[1]: Stopping FlexGet...
> Apr 05 09:47:11 LibreELEC sh[27599]: Traceback (most recent call last):
> Apr 05 09:47:11 LibreELEC sh[27599]:   File "/storage/.kodi/addons/service.flexget/bin/flexget_vanilla.py", line 3, in <module>
> Apr 05 09:47:11 LibreELEC sh[27599]:     import flexget
> Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/__init__.py", line 12, in <module>
> Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/manager.py", line 37, in <module>
> Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/db_schema.py", line 14, in <module>
> Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/database.py", line 14, in <module>
> Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/json.py", line 12, in <module>
> Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/plugin.py", line 11, in <module>
> Apr 05 09:47:11 LibreELEC sh[27599]: ImportError: No module named pkg_resources
> Apr 05 09:47:12 LibreELEC systemd[1]: service.flexget.service: Main process exited, code=exited, status=1/FAILURE
> Apr 05 09:47:14 LibreELEC sh[27628]: Traceback (most recent call last):
> Apr 05 09:47:14 LibreELEC sh[27628]:   File "/storage/.kodi/addons/service.flexget/bin/flexget_vanilla.py", line 3, in <module>
> Apr 05 09:47:14 LibreELEC sh[27628]:     import flexget
> Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/__init__.py", line 12, in <module>
> Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/manager.py", line 37, in <module>
> Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/db_schema.py", line 14, in <module>
> Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/database.py", line 14, in <module>
> Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/json.py", line 12, in <module>
> Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/plugin.py", line 11, in <module>
> Apr 05 09:47:14 LibreELEC sh[27628]: ImportError: No module named pkg_resources
> Apr 05 09:47:15 LibreELEC systemd[1]: service.flexget.service: Control process exited, code=exited status=1
> Apr 05 09:47:15 LibreELEC systemd[1]: service.flexget.service: Failed with result 'exit-code'.
> Apr 05 09:47:15 LibreELEC systemd[1]: Stopped FlexGet.
> ```
> What's wrong? setuptools is missing for some reason...
> 
> EDIT: I discovered that all the dependencies in pre_make_target are ignored, so you can't find any of them in the latest package. Do you know why? Thanks.

**Comment by konstiv73** [comment]
> > I have this error:
> > ```
> > Apr 05 09:46:48 LibreELEC systemd[1]: Started FlexGet.
> > Apr 05 09:46:51 LibreELEC systemd[1]: Stopping FlexGet...
> > Apr 05 09:47:11 LibreELEC sh[27599]: Traceback (most recent call last):
> > Apr 05 09:47:11 LibreELEC sh[27599]:   File "/storage/.kodi/addons/service.flexget/bin/flexget_vanilla.py", line 3, in <module>
> > Apr 05 09:47:11 LibreELEC sh[27599]:     import flexget
> > Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/__init__.py", line 12, in <module>
> > Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/manager.py", line 37, in <module>
> > Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/db_schema.py", line 14, in <module>
> > Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/database.py", line 14, in <module>
> > Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/json.py", line 12, in <module>
> > Apr 05 09:47:11 LibreELEC sh[27599]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/plugin.py", line 11, in <module>
> > Apr 05 09:47:11 LibreELEC sh[27599]: ImportError: No module named pkg_resources
> > Apr 05 09:47:12 LibreELEC systemd[1]: service.flexget.service: Main process exited, code=exited, status=1/FAILURE
> > Apr 05 09:47:14 LibreELEC sh[27628]: Traceback (most recent call last):
> > Apr 05 09:47:14 LibreELEC sh[27628]:   File "/storage/.kodi/addons/service.flexget/bin/flexget_vanilla.py", line 3, in <module>
> > Apr 05 09:47:14 LibreELEC sh[27628]:     import flexget
> > Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/__init__.py", line 12, in <module>
> > Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/manager.py", line 37, in <module>
> > Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/db_schema.py", line 14, in <module>
> > Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/database.py", line 14, in <module>
> > Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/utils/json.py", line 12, in <module>
> > Apr 05 09:47:14 LibreELEC sh[27628]:   File "/home/thoradia/Projects/thoradia/9.0/build.LibreELEC-RPi.arm-9.0-devel/flexget-2.17.22/.install_pkg/usr/lib/python2.7/site-packages/FlexGet-2.17.22-py2.7.egg/flexget/plugin.py", line 11, in <module>
> > Apr 05 09:47:14 LibreELEC sh[27628]: ImportError: No module named pkg_resources
> > Apr 05 09:47:15 LibreELEC systemd[1]: service.flexget.service: Control process exited, code=exited status=1
> > Apr 05 09:47:15 LibreELEC systemd[1]: service.flexget.service: Failed with result 'exit-code'.
> > Apr 05 09:47:15 LibreELEC systemd[1]: Stopped FlexGet.
> > ```
> > What's wrong? setuptools is missing for some reason...
> > EDIT: I discovered that all the dependencies in pre_make_target are ignored, so you can't find any of them in the latest package. Do you know why? Thanks.

I have same.

**Comment by thoradia** [comment]
It should be fixed with revision 11

**Comment by konstiv73** [comment]
It works!
