### ISSUE TITLE
radarr cant update

### ISSUE THREAD

**Issue by alsdfjldafsjalsfjk** [thoradia/LibreELEC.tv#59]
Hello! I have some problems maybe someone can help?

If i click the install latest button it notifies that it starts downloading but it never does, if i then click the button again it says;

> Verifying update package

again nothing happens so i click button again; 

> Extracting Update package

and for each of the following lines i need to click install latest;

> Update package extracted successfully

click install latest;

> Starting Backup

click install latest;

> Preparing client

click install latest;

> Starting update client /tmp/radarr_update/Radarr.Update.exe

click install latest;

> Radarr will restart shortly.

click install latest;

> Updater Arguments: 10860 /tmp/radarr_update /storage/.kodi/addons/service.radarr/radarr/Radarr.exe /data=/storage/.kodi/userdata/addon_data/service.radarr /nobrowser

and finally, click install latest;

> Starting 2 threads for tasks.

But it never restarts or anything. If i manually restart nothing gets installed - any ideas what can be wrong or how i can fix this?

tyvm

**Comment by alsdfjldafsjalsfjk** [comment]
tried to reinstall / delete addon data - but still the same result: i cant update to v. 0.2.0.1344 :(

**Comment by thoradia** [comment]
This is fixed with latest jackett/radarr/sonarr addons
[Enable swap](https://forum.libreelec.tv/thread/15109-how-to-enable-swapfile-on-libreelec/?postID=115507#post115507) to prevent addons from freezing your system

**Comment by alsdfjldafsjalsfjk** [comment]
Update fixed it, i also added the swapfile for future! Thank you!
