### ISSUE TITLE
Startup issue build /7.0/S905/aarch64

### ISSUE THREAD

**Issue by Ronflexx** [thoradia/LibreELEC.tv#6]
Hello

I can't make this build working on Beelink MiniMXIII S905 running on 7.2.0-009 build taken out from here https://forum.libreelec.tv/thread-2347.html.

I tried the following build https://github.com/thoradia/thoradia/tre...05/aarch64.
The package are successfully installed, but there are not starting either within the GUI or cli.

Daemon is not starting, if I launch manually the service I got the help options.

Do you have any hint ?

Here is the result of a startup attempt : 
 /storage/.kodi/addons/service.transmission/bin/transmission.start
net.core.rmem_max = 4194304
net.core.wmem_max = 1048576
Transmission 2.92 (14714)  http://www.transmissionbt.com/
A fast and easy BitTorrent client

transmission-daemon is a headless Transmission session
that can be controlled via transmission-remote
or the web interface.

Usage: transmission-daemon [options]

**Comment by thoradia** [comment]
What are the add-on settings, in /storage/.kodi/userdata/addon_data/service.transmission/settings.xml?

**Comment by Ronflexx** [comment]
<settings>
    <setting id="tx_allowed" value="*.*.*.*" />
    <setting id="tx_download" value="/var/media/My Passport/Téléchargements/" />
    <setting id="tx_incomplete" value="/var/media/My Passport/Téléchargements/encours/" />
    <setting id="tx_password" value="" />
    <setting id="tx_port" value="9091" />
    <setting id="tx_separate_incomplete" value="true" />
    <setting id="tx_username" value="" />
    <setting id="tx_watch" value="/storage/.kodi/userdata/addon_data/service.transmission/watch" />
</settings>

**Comment by thoradia** [comment]
Transmission has issues with the space in the name of your external drive.
I will see how to fix.
In the meantime, you could relabel your external drive, MonPasseport for instance.

**Comment by Ronflexx** [comment]
Thanks for your support, Transmission has started !

And thanks for releasing this addons
