### ISSUE TITLE
How to disable --on-active

### ISSUE THREAD

**Issue by HorstBrack75** [thoradia/LibreELEC.tv#61]
Maybe a stupid question, but how to configure to NOT run after every reboot?

Is there an easy way, like entering --on-active -1 in the configuration panel? 

The grabbing takes some hours. I am fine to do it at 3AM.
I can´t enter --on-activce"03h00m" cause it is a numerical input field. Additionally the --on-calendar already does this.

THX

**Comment by thoradia** [comment]
The script ignores --on-active when it is an empty string

**Comment by HorstBrack75** [comment]
How can I achieve this? If I try to enter an empty string for --on-active via the addon configuration gui, it will reset the value to 300. The input box will not accept an empty string for --on-active in the configuration panel.

I tried to set the string to empty manually in the settings xml file.

&lt;settings version="2"&gt;
&lt;setting id="wgp_nice">10&lt;/setting&gt;
&lt;setting id="wgp_on_act" default="false"&gt;&lt;/setting&gt; (Tried "true" as well, no effect.)
&lt;setting id="wgp_on_cal" default="true"&gt;*-*-* 03:00:00&lt;/setting&gt;

It has no effect. WebGrab runs anyway upon reboot.

THX

**Comment by thoradia** [comment]
Fixed with 755f037 for LibreELEC 9.2

Operative fix is https://github.com/thoradia/LibreELEC.tv/blob/755f0374105ff4286d845858d0ae5e5f5c1ef59c/packages/thoradia/addons/webgrabplus/source/bin/webgrabplus.start

If you need the fix for other versions of LibreELEC edit webgrabplus.start accordingly

**Comment by HorstBrack75** [comment]
That looks great. Thank you for the quick reply.

I need it for RPi2, ARM, LibreELEC 9.02.

I will try if I can build it myself :-)

**Comment by thoradia** [comment]
No need to build
ssh to LibreELEC, `nano $(which webgrabplus.start)`, then copy/paste the fix

**Comment by HorstBrack75** [comment]
Thanks!
I now set -1 and WebGrab does not start upon reboot!

THX
