### ISSUE TITLE
FlexGet addon configuration

### ISSUE THREAD

**Issue by DavidDiazGuerra** [thoradia/LibreELEC.tv#64]
Hello!

I have installed the FlexGet addon from your repository, but I am having troubles to configure it. I found the file `/storage/.kodi/addons/service.flexget/config/config.yml` and replaced it by a config file that I have working in another RasPi with xBian and FlexGet through with pip, but nothing appears in Transmission. Do you know if editing that file is the correct way to configure the FlexGet addon? 

By the way, do you know how to execute FlexGet manually (in order to run `flexget --test execute`) or where are the log files? It would help to debug the issue.

Thanks!

**Comment by thoradia** [comment]
FlexGet configuration is `/storage/.kodi/userdata/addon_data/service.flexget/config.yml`

To execute FlexGet manually, use command `flexget.ctl`

**Comment by DavidDiazGuerra** [comment]
It works now, thank you very much!
