### ISSUE TITLE
thoradia add on can not run in libreelec 9x

### ISSUE THREAD

**Issue by wuypinfo** [thoradia/LibreELEC.tv#66]
thoradia add on can not run in libreelec 9x. Can you compile it again? or tell me how to compile transmission add on. downloand the source.tar, how to compile?

**Comment by thoradia** [comment]
Add-ons for LibreELEC 9.1 will be updated soon

**Comment by thoradia** [comment]
I have rebuilt add-ons for LibreELEC 9.1 (ADDON_VERSION=9.80.1) for Generic, RPi2 and RPi4
They are pre-alpha, expect breakage

**Comment by wuypinfo** [comment]
thank you ,but  my tv box is Amlogic S905D. I test it.

**Comment by thoradia** [comment]
Try to install [this](https://github.com/thoradia/thoradia/blob/master/9.80.1/RPi2/arm/service.transmission/service.transmission-9.80.1.16.zip) and let me know if it runs

**Comment by wuypinfo** [comment]
very good, the software can work at my tv box(S905D+libreelec+18.3kodi+5.2.1kernel),thank you.

**Comment by thoradia** [comment]
Thank you for the feedback @wuypinfo 

Could you please provide me with the output of
`more /usr/share/kodi/addons/repository.libreelec.tv/addon.xml`

With this information I can update Thoradia Add-ons repository for Amlogic to use the add-ons for RPi2

**Comment by wuypinfo** [comment]
[addon.zip](https://github.com/thoradia/LibreELEC.tv/files/3557746/addon.zip)

see attached. I compile the rom from https://github.com/150balbes/LibreELEC.tv when kernel is 5.2.1,and now 150balbes up kernel to 5.3.x

thank you again. very nice add on.

**Comment by thoradia** [comment]
This repository should enable to install/update add-ons on Amlogic devices
[service.thoradia-9.80.1.21.zip](https://github.com/thoradia/LibreELEC.tv/files/3558563/service.thoradia-9.80.1.21.zip)

If it works for you I will merge the changes

**Comment by wuypinfo** [comment]
It can be installed and requirt kodi restart. but it can not download. It say: Could not connect to repository. and at same time, other add on can be down, such as weather.

**Comment by thoradia** [comment]
ADDON_VERSION is 9.80.0 at 150balbes and 9.80.1 at LibreELEC
I will try to find an easy workaround

**Comment by marpemim** [comment]
I have installed the repo in coreelec but i try to open the repo to install addon and it show can not connect to the repo, why?

**Comment by thoradia** [comment]
@marpemim 
Please do not
- hijack issues
- cross post

See #67
