### ISSUE TITLE
Unable to connect to repository from CoreELEC 9.2 nightly

### ISSUE THREAD

**Issue by thoradia** [thoradia/LibreELEC.tv#67]
From @marpemim:
I have installed the repo in coreelec but i try to open the repo to install addon and it show can not connect to the repo, why?

**Comment by thoradia** [comment]
What version of CoreELEC are you running?
What is the output of `more /usr/share/kodi/addons/repository.libreelec.tv/addon.xml`?

**Comment by marpemim** [comment]
I use CoreELEC-Amlogic-ng.arm-9.1-nightly_20190902-Generic.img.gz 177.82MB 2019-09-03 02:28:43 in Beelink GT king and khadas vim3.
I try to find  this path more /usr/share/kodi/addons/repository.libreelec.tv/addon.xml, but it not exist.

I found `/usr/share/kodi/addons/os.libreelec.tv/addon.xml` i do not know if it is valid for you.

This file show this.

`<?xml version="1.0" encoding="UTF-8"?>
<addon id="os.libreelec.tv" version="9.1" provider-name="LibreELEC.tv">
  <requires>
    <import addon="xbmc.addon" version="12.0"/>
  </requires>
</addon>
`

**Comment by marpemim** [comment]
![imagen](https://user-images.githubusercontent.com/48176784/64193449-ab7af100-ce74-11e9-9728-2f26c96aa4f3.png)

**Comment by thoradia** [comment]
CoreELEC has added yet another repository
What is in `/usr/share/kodi/addons/repository.cenightly/addon.xml`?
Maybe this add-on works: [service.thoradia-9.2.22.zip](https://github.com/thoradia/LibreELEC.tv/files/3572698/service.thoradia-9.2.22.zip)

**Comment by marpemim** [comment]
Perfect, now it work in CE nightly. 

Thanks

**Comment by thoradia** [comment]
I will update Thoradia add-ons in the coming days
In the meantime CoreELEC 9.2 nightly users should install from the above zip file

**Comment by thoradia** [comment]
I have updated the bootstrap add-on
https://raw.githubusercontent.com/thoradia/thoradia/master/service.thoradia.zip
Let me know if it works, so that I can close this issue

**Comment by thoradia** [comment]
Assumed solved

**Comment by ulloa** [comment]
I tried the latest zip and i couldn't connect using Coreelec. The old service.thoradia-9.2.22.zip from the previous post still works.
