### ISSUE TITLE
Update Bazarr

### ISSUE THREAD

**Issue by MarkHaakman** [thoradia/LibreELEC.tv#68]
Hi,

Thanks for this amazing repo! As it is not possible to update Bazarr from the web interface, could you perform an update in the repository to the newest version v0.8.1?

Thanks in advance!

**Comment by thoradia** [comment]
On what system do you need it?

**Comment by MarkHaakman** [comment]
Linux-4.19.23-armv7l-with-glibc2.4 (Libreelec 9 on a Raspberry PI)

-------- Original Message --------

**Comment by thoradia** [comment]
LibreELEC 9.0.x on Raspberry Pi?

**Comment by MarkHaakman** [comment]
Yes :)

-------- Original Message --------

**Comment by thoradia** [comment]
Bazarr is updated for LibreELEC 9.0.x

**Comment by MarkHaakman** [comment]
Thank you very much!
