### ISSUE TITLE
Sonarr, Radarr, Lidarr and Jackett stopped working.

### ISSUE THREAD

**Issue by Chuchzilla** [thoradia/LibreELEC.tv#69]
Firstly. Sorry for not providing logs and such upfront but I'm not sure what info would be useful or where it is.

I'm running Libreelec 9.1.501 on a RockPi4. Yesterday sometime sonarr radarr lidarr and jackett all simply stopped running at the same time as far as I can tell. Deluge is still working fine. Reboots do nothing and I tried rolling back versions but nothing. I'm not really savvy enough to diagnose further, so I'm clueless as to the cause.

**Comment by thoradia** [comment]
Your issue is difficult to assess without logs
It is likely a Mono issue
Verify that you have 400 MB free space in /storage and try re-installing Mono
To re-install Mono, simply update to latest version

**Comment by Chuchzilla** [comment]
I have plenty of space in storage but updating mono hangs at installing 33%

[kodi.log](https://github.com/thoradia/LibreELEC.tv/files/3698982/kodi.log)

**Comment by thoradia** [comment]
The log shows Mono is being downloaded and unzipped
Give it another try, be patient

**Comment by Chuchzilla** [comment]
I left it overnight and it installed but didn't fix the issue. I tried again and it's been stuck on installing 33% for about two hours now. That just seems excessive and I'd imagine there's something else going on. I'm going to rebuild the whole machine.
