### ISSUE TITLE
nzbget debug logs?

### ISSUE THREAD

**Issue by alsdfjldafsjalsfjk** [thoradia/LibreELEC.tv#70]
Hi! :)

Im having some issues related to SSL (Could not read from TLS-Socket: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac) and im trying to solve it by enabling debug mode - but either im looking for the logs in the wrong place (LibreELEC:~/.kodi/userdata/addon_data/service.nzbget) or maybe nzbget is compiled without debug enbabled (./configure --enable-debug) ?

Any ideas? Thanks!

**Comment by thoradia** [comment]
`journalctl -u service.nzbget` provides a log
Where nzbget writes the log is specified in the configuration. Check the location that you specified

**Comment by alsdfjldafsjalsfjk** [comment]
`journalctl -u service.nzbget` basically empty only says: 

> -- Logs begin at Fri 2019-10-11 13:22:35 CEST, end at Sat 2019-10-12 15:58:22 CEST. --
> -- No entries --

I have checked nzbget addon settings in kodi aswell as nzbget actual settings via the web-interface and I cant find any where else that contains logs - and the nzbget(date).log file contains error/info/detail but no debug in sight

![nzbget-Screenshot from 2019-10-12 16-03-58](https://user-images.githubusercontent.com/10330216/66702629-f73d7780-ed09-11e9-8ff6-9148d3264f10.jpg)

What am i not understanding?

**Comment by thoradia** [comment]
Provide more information
On what are you running nzbget? LibreELEC or CoreELEC? What version? For what system?
Also, what are you trying to do when you have this issue?

**Comment by alsdfjldafsjalsfjk** [comment]
> Provide more information
> On what are you running nzbget? LibreELEC or CoreELEC? What version? For what system?
> Also, what are you trying to do when you have this issue?

Sorry!

im running LibreELEC (official): 9.0.2 (Generic.x86_64) on a Intel NUC NUC7i3BNH. When i download via nzbGet version 21.0 and have SSL enabled i get the error: `Could not read from TLS-Socket: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac`

I would like to get rid of it and i think i need to enable debug logging to even start being helpful when submitting my error to the nzbget dev(s).

**Comment by thoradia** [comment]
This is built with `--enable-debug`: [x86_64/Generic/service.nzbget-9.0.16.1.zip](https://github.com/thoradia/LibreELEC.tv/files/3735921/service.nzbget-9.0.16.1.zip)

**Comment by alsdfjldafsjalsfjk** [comment]
Thank you!! Please know im totally unaware of how much harder it might be building with/without debug - but if u could, please build it with debug enabled in the future - i think it would be good! 

Either way, ill try to get this going during the weekend and if i find anything i think you might want to know ill get back to you! 

Again, thanks for this! :)
