### ISSUE TITLE
The Download does not complete

### ISSUE THREAD

**Issue by Marcelopsico** [thoradia/LibreELEC.tv#71]
Every time I try do Download the .zip file, it crashes near 2 gb. I'm using Google Chrome. Can anyone help me? 

![print](https://user-images.githubusercontent.com/56516035/66719787-890cb980-edca-11e9-99c1-a112c3fcc4aa.png)

**Comment by thoradia** [comment]
Download and install [this](https://raw.githubusercontent.com/thoradia/thoradia/master/service.thoradia.zip)
