### ISSUE TITLE
aria2 addon update to 1.35.0

### ISSUE THREAD

**Issue by seanrand** [thoradia/LibreELEC.tv#72]
It would be great if you could update aria2 to 1.35.0, it would resolve some longstanding issues (specifically with tls/ca-certs on https downloads). With 1.34.0 I'm unable to download anything from https, even with --check-certificate=false.

For the time being, I've replaced the aria2 binary in the addon with [this Linux 64 static build binary v1. 35](https://github.com/q3aql/aria2-static-builds/blob/master/README.md#aria2-1350-builds-with-openssl), downloaded the [ca-certificates.crt](https://github.com/q3aql/aria2-static-builds/blob/master/README.md#ca-certificates-on-windows-https) to `addon_data/service.aria2/`  and added 
```
ca-certificate=/storage/.kodi/userdata/addon_data/service.aria2/ca-certificates.crt
```
to my aria2.conf. Seems to work so far.

**Comment by thoradia** [comment]
For what release of LibreELEC?
Aria2 1.35.0 is available for LibreELEC 9.2

**Comment by seanrand** [comment]
Oh, didn't realise. I'm running Milhouse 9.8 here.

**Comment by thoradia** [comment]
See [here](https://github.com/thoradia/LibreELEC.tv/issues/82#issuecomment-664873168)
