### ISSUE TITLE
transmission - request - add cli tools

### ISSUE THREAD

**Issue by UmpPCPL** [thoradia/LibreELEC.tv#73]
Hi
It would be great to have cli for transmission included in the package.
Why:
CLI allows scripting of transmission from  LibreELEC command line.
  (adding / monitoring / removing of downloads)
In past it was already part of transmission addon ( OpenELEC times )

The footprint of additional binaries is quite low:  ~1MB

How: 
 I believe it is just matter of enabling it in package.mk -DENABLE_CLI=ON
Outcome:
 transmission-remote binary as part of add-on

Thanks a lot.
Michal

**Comment by thoradia** [comment]
Done for LibreELEC 9.2

**Comment by UmpPCPL** [comment]
Thanks a lot. Works as expected.

**Comment by uorbe001** [comment]
Where would the transmission-remote binary be located? I'm on `LibreELEC (official): 9.2.3` and I can't find the transmission-remote, but I can see the cli on `/storage/.kodi/addons/service.transmission/bin/transmission-cli`.

Am I looking in the wrong place?

EDIT: Also, running `find / -name 'transmission-remote'` fetches no results, while it does for the cli.

**Comment by uorbe001** [comment]
Ahh, this only enables the transmission-cli these days, a different makefile option is needed for this. I've [opened a PR](https://github.com/thoradia/LibreELEC.tv/pull/84) and you can reject it if you don't agree with having that 😉
