### ISSUE TITLE
Can't update Mono ("Installing 33%")

### ISSUE THREAD

**Issue by edjalmobf** [thoradia/LibreELEC.tv#78]
After update to LibreELEC 9.2.0 I can't update Mono. It always get's stuck at "installing 33%".
I already tried stop all the add-ons that use it (because I thought it can't update because still running, but without success).

Hardware: rPI 3b

**Comment by thoradia** [comment]
Do you have enough room in /storage?

**Comment by edjalmobf** [comment]
Yes!
![Screenshot_20191222-134602](https://user-images.githubusercontent.com/42322017/71324785-e8213580-24c1-11ea-8acc-d77ca6a6f05f.png)

**Comment by thoradia** [comment]
Closing in favor of #79 which proposes a solution
