### ISSUE TITLE
Can´t install mono on LibreELEC 9.2.2

### ISSUE THREAD

**Issue by ghost** [thoradia/LibreELEC.tv#79]
I have the same problem like the other issue. The installation stops at 33%. I doesn´t matter if i install from mono directly or by the addon webgrab+ itself - then the installation stops at 25 %. On /storage  is around 45 GB free

**Comment by ghost** [comment]
Solution:
+ download the tools.mono.xyz and extract it in a directory of your choice
+ copy the tool.mono directory to /storage/.kodi/addons
+ activate the addon in kodi interface
+ install webgrab plus from repository as usual

**Comment by thoradia** [comment]
Thank you for reporting this issue and proposing a solution
I keep this issue open until its cause is documented with a log and fixed

**Comment by edjalmobf** [comment]
@TCRW I tried use your solution but I could not.
I downloaded this [file](https://github.com/thoradia/thoradia/blob/master/9.2.0/RPi2/arm/tools.mono/tools.mono-9.2.0.117.zip), extract and copied to /storage/.kodi/addons but didn't work.
Can you explain more detailed?

**Comment by thoradia** [comment]
@edjalmobf 
Check that directory `/storage/.kodi/addons/tools.mono` exists and contains file `addon.xml`
Then go in the Kodi add-on manager
Mono should be installed but disabled (if not restart Kodi)
Enable Mono

I am still trying to determine the cause of this issue
It could be related to memory.

**Comment by edjalmobf** [comment]
@thoradia work like a charm 👍 
To help someone else, here the steps I did:

Go to Kodi add-on manager and disabler Mono (maybe you need disabler the add-ons that use it too, like sonarr/radarr)
Go to terminal and type:
```
cd downloads/

curl -LO https://github.com/thoradia/thoradia/raw/master
/9.2.0/RPi2/arm/tools.mono/tools.mono-9.2.0.117.zip (this version of mono is from a rPI3, change it for you system)

unzip tools.mono-9.2.0.117.zip -d /storage/.kodi/addons/
```
Reboot the device and after enable Mono
Thanks @thoradia and @TCRW

**Comment by thoradia** [comment]
This issue is likely due to the fact that some processes, in particular add-on installation and update, use the `/tmp` directory
On LibreELEC, the `/tmp` directory resides in RAM and there is no swap space
Filling the `/tmp` therefore causes problems
Add-ons have been fixed to use another directory
