### ISSUE TITLE
Transmission unable to start on s905 device with LE 7.0.12(32bit).

### ISSUE THREAD

**Issue by leximester** [thoradia/LibreELEC.tv#8]

**Comment by thoradia** [comment]
Please provide a log (journalctl -u service.transmission)

**Comment by thoradia** [comment]
Rebased S905 against 7.3.0.012, and attempting a rebuild

**Comment by leximester** [comment]
Yes, I was wrong it is the 7.0.3.012 from kszaq. Thank you.

**Comment by thoradia** [comment]
Updated. Please test and report if it fixes.

**Comment by BaZSeE89** [comment]
It's good, working for me, but 1 hour ago sonar disappeared from a list.

**Comment by thoradia** [comment]
Closing the Transmission issue.

@BaZSeE89 
Check for addons/repositories updates.
Sonarr requires Mono, from LibreELEC repository.
Open a separate issue if problem persists.

**Comment by leximester** [comment]
Working for me too. Thank you the fast solution!
