### ISSUE TITLE
Transmission, 403: Forbidden

### ISSUE THREAD

**Issue by NickTretiakov** [thoradia/LibreELEC.tv#80]
Hi,
Recently after no changes made in configuration or wherever, I started seeing this error when accessing web interface:
403: Forbidden
Too many unsuccessful login attempts. Please restart transmission-daemon.

That is also a case when I restart the service i.e.
Is there a way to remove a limit of failed attempts or perhaps fix it in another way?

**Comment by thoradia** [comment]
Check/update `/storage/.kodi/userdata/addon_data/service.transmission/settings.json`

**Comment by NickTretiakov** [comment]
checked it, didn't see anything related.
is it "nice" field in another config named settings.xml?

**Comment by thoradia** [comment]
[nice](https://linux.die.net/man/1/nice) has nothing to do with this issue
Someone might be able to help if you provide more details
Provide a log (`journalctl -u service.transmission`) and your settings.json (remove the rpc-username and rpc-password lines)

**Comment by thoradia** [comment]
Inactive, closing
