### ISSUE TITLE
Deluge is not working on LibreELEC 9.2.3

### ISSUE THREAD

**Issue by evanre** [thoradia/LibreELEC.tv#81]
Hey, I'm running LibreELEC 9.2.3 on RPi4. Installed Throadia Add-ons (v9.2.0.23) and Deluge addon (v9.2.0.31). It appears in ssh path but I can't run it:

> pi4:~ # deluged
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.deluge/bin/deluged", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
pi4:~ # deluge-web
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.deluge/bin/deluge-web", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by thoradia** [comment]
The deluge add-on is configured to automatically start system.d services
You should therefore not need to start deluged or deluge-web manually
If you nevertheless want to, you can use the `deluged.start` and `deluge-web.start` wrapper scripts

**Comment by thoradia** [comment]
Inactive, closing

**Comment by evanre** [comment]
@thoradia I got it, thank you! Sorry for long response.
