### ISSUE TITLE
thoradia compatible with python 3.0.0

### ISSUE THREAD

**Issue by Tristreeple** [thoradia/LibreELEC.tv#82]
Hello, 

Thanks for your job. Now, I use LibreELEC (Milhouse): devel-20200718000045-#0717-g776b589 [Build #0717]. This version is based on Kodi 19 with python 3.0.0.

If is it possible, could you please update your repositories and addons for work it ?

Thanks so mutch.

**Comment by thoradia** [comment]
Add-ons for LibreELEC 9.80 are [here](https://github.com/thoradia/thoradia/tree/9.80.4)
You can try to install [this](https://github.com/thoradia/thoradia/blob/9.80.4/9.80.4/RPi2/arm/service.thoradia/service.thoradia-9.80.4.24.zip)

**Comment by Tristreeple** [comment]
Thanks you so much for your reply :)

**Comment by Tristreeple** [comment]
Could you please reset the transmission service configuration? In the previous version, we could configure directories. In this version (9.80.4.22), the only parameter is "Nice".

Thank you so much for your answers and your job.

**Comment by Tristreeple** [comment]
> Add-ons for LibreELEC 9.80 are [here](https://github.com/thoradia/thoradia/tree/9.80.4)
> You can try to install [this](https://github.com/thoradia/thoradia/blob/9.80.4/9.80.4/RPi2/arm/service.thoradia/service.thoradia-9.80.4.24.zip)

Tkx for your answers, 

I have an suggestions for you. Could you please reset the transmission service configuration? In the previous version, we could configure directories. In this version (9.80.4.22), the only parameter is "Nice".

Thank you so much for your answers and your job.

**Comment by thoradia** [comment]
Closing this
Keep issues on topic
Transmission issue is dealt with #83
