### ISSUE TITLE
8.1\S905\arm

### ISSUE THREAD

**Issue by BaZSeE89** [thoradia/LibreELEC.tv#9]
Hy!
I'm testing LibreELEC-S905.arm-8.0-7.90.beta1 kszaq build on my device. It will be good to use this repo on that build. Is that possible? 

Thanks your answer!

Bazsee

**Comment by thoradia** [comment]
8.1/S905/arm has not yet been built. If you tell me where I can find the source, I will try to build it.

**Comment by thoradia** [comment]
Done
