### ISSUE TITLE
Jackett service failing to start

### ISSUE THREAD

**Issue by jaum20** [thoradia/LibreELEC.tv#94]
Running LibreELEC on an Arm32 device
Jackett service is failing to start. Also, there is no 'JackettConsole.exe' in /libs. If I run ` /libs/jackett` it gives a error:

`Illegal instruction`

I manually downloaded the mono version of jackett and tried to run `mono libs/JackettConsole.exe` it gives the same error

**Comment by thoradia** [comment]
Thank you for your feedback.

From [the information you provide on the LibreELEC forum](https://forum.libreelec.tv/thread/2707-thoradia-add-ons/?postID=144815#post144815), you are trying to run Jackett on LibreELEC 9.2 for [RK222x](https://forum.libreelec.tv/thread/21117-unoffical-le-9-2-9-80-images-for-rk3229-rk3228/?pageNo=1)
On arm devices, the add-on downloads and runs Jackett for .Net Core, whose executable is `libs/jackett`

`Illegal instruction` could be a symptom of [a mismatch between the requirements of .Net Core and the features of your processor](https://github.com/dotnet/runtime/issues/9969), which may also affect other binaries.

Please provide the output of `cat /proc/cpuinfo` 

To see if the Mono version of Jackett works on your system, 'update' the add-on to revision 43 and disable auto-update with the Kodi add-on manager

**Comment by jaum20** [comment]
Output of ` cat proc/cpuinfo`:

```
processor: 0
model name: ARMv7 Processor rev 5 (v7l)
BogoMIPS: 24.00
Features: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer: 0x41
CPU architecture: 7
CPU variant: 0x0
CPU part: 0xc07
CPU revision: 5

processor: 1
model name: ARMv7 Processor rev 5 (v7l)
BogoMIPS: 24.00
Features: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer: 0x41
CPU architecture: 7
CPU variant: 0x0
CPU part: 0xc07
CPU revision: 5

processor: 2
model name: ARMv7 Processor rev 5 (v7l)
BogoMIPS: 24.00
Features: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer: 0x41
CPU architecture: 7
CPU variant: 0x0
CPU part: 0xc07
CPU revision: 5

processor: 3
model name: ARMv7 Processor rev 5 (v7l)
BogoMIPS: 24.00
Features: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer: 0x41
CPU architecture: 7
CPU variant: 0x0
CPU part: 0xc07
CPU revision: 5

Hardware: Generic DT based system
Revision: 0000
Serial: eda6fcbcc20d889
```

The revision 43 is working fine on my system.

**Comment by thoradia** [comment]
Glad to read that Jackett for Mono runs on your system

Can you tell me if the latest revision of Radarr also throws an `Illegal instruction` on your system?

I could adjust add-ons to use Mono on your system, but I would like to pinpoint the proper add-on/device/project

**Comment by jaum20** [comment]
Yes, same error with the latest revision of Radarr.

**Comment by thoradia** [comment]
I do not build add-ons for RK222x and I do not have the time to
RK222x uses the add-ons built for RPi2, which is able to run .Net Core runtime
RK222x is however not able to run .Net Core runtime
A solution would therefore be to install the [Jackett](https://github.com/thoradia/thoradia/raw/master/9.2.0/RPi/arm/service.jackett/service.jackett-9.2.0.50.zip) and [Radarr](https://github.com/thoradia/thoradia/raw/master/9.2.0/RPi/arm/service.radarr/service.radarr-9.2.0.35.zip) add-ons for RPi, which use Mono
If they run, disable auto-update in the Kodi add-on manager to avoid having to re-install the add-ons manually
These add-ons are bootstraps and should not require frequent updates

**Comment by jaum20** [comment]
Can I choose RPi versions of the addons using kodi? Or do I have to install them manually?

**Comment by thoradia** [comment]
You have to install them manually, because your repository points to add-ons for RPi2
You could maybe report to @knaerzche that .Net Core fails with an illegal instruction on his build that you are using
