### ISSUE TITLE
Update Bazarr

### ISSUE THREAD

**Issue by frestalink** [thoradia/LibreELEC.tv#95]
Hi,
Could you please update Bazarr on LIBREELEC 9.2.4 on Raspberry PI 3?
Thanks!

**Comment by thoradia** [comment]
Latest [Bazarr requires Python 3](https://github.com/morpheus65535/bazarr/blob/master/bazarr.py#L14-L27)
LibreELEC 9.2 only ships Python 2
Bazarr 0.9.0.5 is available for LibreELEC nightlies
