### ISSUE TITLE
Sonarr doesn't correctly start on boot

### ISSUE THREAD

**Issue by daanveraart** [thoradia/LibreELEC.tv#96]
When Libreelec boots Sonarr fails to start:
Nov 16 13:24:53 mediaserver systemd[1]: Started Sonarr.
Nov 16 13:24:53 mediaserver service.sonarr[515]: wget: bad address 'services.sonarr.tv'
Nov 16 13:24:53 mediaserver service.sonarr[515]: tar: invalid magic
Nov 16 13:24:53 mediaserver service.sonarr[515]: tar: short read
Nov 16 13:24:53 mediaserver systemd[1]: service.sonarr.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 13:24:53 mediaserver systemd[1]: service.sonarr.service: Failed with result 'exit-code'.
Nov 16 13:24:54 mediaserver systemd[1]: service.sonarr.service: Service RestartSec=100ms expired, scheduling restart.
Nov 16 13:24:54 mediaserver systemd[1]: service.sonarr.service: Scheduled restart job, restart counter is at 2.

rebooting it manually using systemctl restart service.sonarr does succesfully start Sonarr, I'm guessing it starts before it has access to the site?

**Comment by thoradia** [comment]
It is always a good idea to set `Wait for network before starting Kodi` in LibreELEC network settings
