### ISSUE TITLE
Update qBittorent to 4.3.0

### ISSUE THREAD

**Issue by SecT0uch** [thoradia/LibreELEC.tv#97]
Hi, 

Would it be possible to update qBittorrent to 4.3.0 ?
I would love to see the RSS functionality in Web UI.

Amazing work, thanks a lot!

**Comment by thoradia** [comment]
The toolchain of LibreELEC 9.2.6 is too old for building qbittorrent 4.3.0
qbittorrent 4.3.1 is available for LibreELEC nightlies
