### ISSUE TITLE
Radarr - The required library libhostfxr.so could not be found

### ISSUE THREAD

**Issue by EnricoK18** [thoradia/LibreELEC.tv#98]
Hi,
after updating to LibreElec 9.2.6 Radarr stopped working. 

The logfiles say:

Jan 06 11:58:10 LibreELEC systemd[1]: Started Radarr.
Jan 06 11:58:10 LibreELEC service.radarr[786]: A fatal error occurred. The required library libhostfxr.so could not be found.
Jan 06 11:58:10 LibreELEC service.radarr[786]: If this is a self-contained application, that library should exist in [/storage/.kodi/addons/service.radarr/libs/].
Jan 06 11:58:10 LibreELEC service.radarr[786]: If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
Jan 06 11:58:10 LibreELEC service.radarr[786]: The .NET Core runtime can be found at:
Jan 06 11:58:10 LibreELEC service.radarr[786]:   - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=libreelec.9.2-x64
Jan 06 11:58:10 LibreELEC systemd[1]: service.radarr.service: Main process exited, code=exited, status=131/n/a
Jan 06 11:58:10 LibreELEC systemd[1]: service.radarr.service: Failed with result 'exit-code'.
Jan 06 11:58:10 LibreELEC systemd[1]: Started NZBGet.
Jan 06 11:58:10 LibreELEC systemd[1]: service.radarr.service: Service RestartSec=100ms expired, scheduling restart.
Jan 06 11:58:11 LibreELEC systemd[1]: service.radarr.service: Scheduled restart job, restart counter is at 1.
Jan 06 11:58:11 LibreELEC systemd[1]: Stopped Radarr.

**Comment by thoradia** [comment]
Please provide the output of `journalctl -u service.radarr`
To fix the issue, re-install the lastest version of Radarr (update in add-on Manager)
Also, make sure that Updates/Branch is master in Settings/General

**Comment by EnricoK18** [comment]
Reinstalling helped. Everything is working fine. Thanks.
